#!/bin/bash

LoadBalancer=192.168.220.100
LoadBalancerPort=6443

ETCD0=etcd0
ETCD1=etcd1
ETCD2=etcd2

cat << EOF > init-config.yaml

apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "${LoadBalancer}:${LoadBalancerPort}"
dns:
  type: CoreDNS
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.96.0.0/12
etcd:
    external:
        endpoints:
        - https://${ETCD0}:2379
        - https://${ETCD1}:2379
        - https://${ETCD2}:2379
        caFile: /etc/kubernetes/etcd.ssl/ca.pem
        certFile: /etc/kubernetes/etcd.ssl/client.pem
        keyFile: /etc/kubernetes/etcd.ssl/client-key.pem
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers

EOF

kubeadm init --config kubeadm-config.yaml --upload-certs


if [[ $? == 0]]
then
	mkdir -p $HOME/.kube
  	sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  	sudo chown $(id -u):$(id -g) $HOME/.kube/config
fi


kubectl apply -f "http://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"


#flannel
#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml


# Install Kubernetes Dashboard UI
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
